export interface EvidencePack {
  id: string;
  title: string;
  category: 'dataset' | 'agent-run' | 'document' | 'manifest';
  sourceType: 'web-scrape' | 'api-export' | 'agent-output' | 'manual-upload';
  tags: string[];
  createdAt: string;
  blobCount: number;
  status: 'active' | 'archived' | 'pending';
  description: string;
  /** Indicates the origin of this record. Undefined means built-in demo data. */
  dataSource?: 'demo' | 'local';
}

export const evidencePacks: EvidencePack[] = [
  {
    id: 'pack-001',
    title: 'Common Crawl Sample — Web Text 2024-Q1',
    category: 'dataset',
    sourceType: 'web-scrape',
    tags: ['common-crawl', 'web-text', 'nlp', '2024'],
    createdAt: '2024-01-15T08:30:00Z',
    blobCount: 2,
    status: 'active',
    description:
      'A curated sample of 50k documents extracted from Common Crawl January 2024 snapshot. Includes deduplicated HTML-stripped text, language-identified as English, with quality filtering applied.',
  },
  {
    id: 'pack-002',
    title: 'GPT-4o Agent Run — Legal Clause Extractor v0.3',
    category: 'agent-run',
    sourceType: 'agent-output',
    tags: ['gpt-4o', 'legal', 'clause-extraction', 'agent-run'],
    createdAt: '2024-02-03T14:22:11Z',
    blobCount: 1,
    status: 'active',
    description:
      'Outputs from a GPT-4o agent tasked with extracting indemnification and liability clauses from 200 SaaS contracts. Includes structured JSON output, confidence scores, and source references.',
  },
  {
    id: 'pack-003',
    title: 'arXiv ML Papers Metadata Export — Feb 2024',
    category: 'manifest',
    sourceType: 'api-export',
    tags: ['arxiv', 'machine-learning', 'metadata', 'research'],
    createdAt: '2024-02-10T09:00:00Z',
    blobCount: 1,
    status: 'active',
    description:
      'Metadata manifest for 3,200 arXiv papers published under cs.LG and cs.AI in February 2024. Includes title, abstract, authors, and submission date. Exported via arXiv OAI-PMH API.',
  },
  {
    id: 'pack-004',
    title: 'Internal Policy Document — Data Governance v2',
    category: 'document',
    sourceType: 'manual-upload',
    tags: ['policy', 'governance', 'internal', 'compliance'],
    createdAt: '2024-03-01T11:45:00Z',
    blobCount: 1,
    status: 'archived',
    description:
      'Version 2 of the internal AI data governance policy. Covers data retention, access controls, bias auditing requirements, and incident response procedures for ML pipelines.',
  },
  {
    id: 'pack-005',
    title: 'Synthetic QA Benchmark — Reasoning Tasks v1',
    category: 'dataset',
    sourceType: 'agent-output',
    tags: ['synthetic', 'qa', 'benchmark', 'reasoning', 'eval'],
    createdAt: '2024-03-18T16:00:00Z',
    blobCount: 1,
    status: 'pending',
    description:
      'Synthetically generated question-answer pairs for evaluating multi-step reasoning in LLMs. 10,000 examples spanning arithmetic, logical deduction, and causal inference. Generated by an LLM pipeline with human spot-check.',
  },
];
